In [22]:
%pip install numpy pandas

Note: you may need to restart the kernel to use updated packages.


In [23]:
import numpy as np
import pandas as pd

In [4]:
print( np.__version__)

2.1.2


In [7]:
Array = np.array( [10, 20, 30, 40, 50] )

In [8]:
type( Array )

numpy.ndarray

In [9]:
Duas_Dimensoes = np.array (
  [
  [10, 0, 20, 40,2],
  [5, 3, 6, 7, 8]
  ]
)

print(Duas_Dimensoes)

[[10  0 20 40  2]
 [ 5  3  6  7  8]]


In [10]:
Tres_Dimensoes = np.array (
  [
  [10, 0, 20, 40,2],
  [5, 3, 6, 7, 8],
  [90, 100, 3, 5, 6]
  ]
)

print(Tres_Dimensoes)

[[ 10   0  20  40   2]
 [  5   3   6   7   8]
 [ 90 100   3   5   6]]


In [11]:
np.arange( 10 )

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Acessar os Arrays
Array[0]

np.int64(10)

In [13]:
Array[-1]

np.int64(50)

In [14]:
Array[2:]

array([30, 40, 50])

In [15]:
Array[2:].sum()

np.int64(120)

In [16]:
Array[0] == Array[2]

np.False_

In [17]:
Array.shape

(5,)

In [18]:
Tres_Dimensoes.shape

(3, 5)

In [19]:
# Loop
for Loop in Array:
  print( Loop )

10
20
30
40
50


In [21]:
# Loop
for Loop in Duas_Dimensoes:
  for Interno in Loop:
    print( Interno )

10
0
20
40
2
5
3
6
7
8


In [28]:
pd.DataFrame( Array )

0
0  10
1  20
2  30
3  40
4  50